name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install assets
        run: npm install

      - name: Build
        run: npm run dist:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/latest-linux.yml
            dist/oerthyon-launcher-*.*.*.AppImage

  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install assets
        run: npm install

      - name: Build
        run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/latest.yml
            dist/oerthyon-launcher-*.*.*.exe
            dist/oerthyon-launcher-*.*.*.exe.blockmap

  build-mac:
    runs-on: macos-latest
    name: Build for MacOS
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install assets
        run: npm install

      - name: Build
        run: npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/latest-mac.yml
            dist/oerthyon-launcher-*.*.*.dmg
            dist/oerthyon-launcher-*.*.*.dmg.blockmap
